# Generated by Django 2.2.10 on 2020-08-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(verbose_name='Путь к файлу')),
            ],
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('width', models.IntegerField(verbose_name='Ширина')),
            ],
        ),
    ]
