# Generated by Django 2.2.10 on 2020-08-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200829_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepath',
            name='file_path',
            field=models.FilePathField(match='*/.csv$', path='/', verbose_name='Путь к файлу'),
        ),
    ]
