# Generated by Django 2.2.10 on 2020-08-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_auto_20200829_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savepath',
            name='file_path',
            field=models.FilePathField(match='#*\\.csv$', path='/', recursive=True, verbose_name='Путь к файлу'),
        ),
    ]
