# Generated by Django 2.2.10 on 2020-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0009_auto_20200829_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvPath', models.CharField(max_length=200, verbose_name='Путь к файлу')),
            ],
            options={
                'verbose_name': 'Путь к файлу',
                'verbose_name_plural': 'Пути к файлам',
            },
        ),
        migrations.DeleteModel(
            name='SavePath',
        ),
    ]
